ARM: versatile: fix build failure in pci.c
1/3 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: ARM: versatile: fix build failure in pci.c
Date: Mon, 2 Apr 2012 19:29:56 -0400

commit 9f786d033d025ab7d2c4d1b959aa81d935eb9e19

    "arm/PCI: get rid of device resource fixups"

causes this failure on the versatile:

arch/arm/mach-versatile/pci.c: In function 'pci_versatile_setup_resources':
arch/arm/mach-versatile/pci.c:221: error: 'sys' undeclared (first use in this function)

because the versatile wasn't passing in the full struct pci_sys_data
but only the resource sub-field.  Change it to pass in the full
struct so that sys will be in scope.

Reported-by: Bruce Ashfield <bruce.ashfield@windriver.com>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

2/3 [
Author: Paul Gortmaker
Email: paul.gortmaker@windriver.com
Subject: irq_work: fix compile failure on MIPS from system.h split
Date: Sun, 1 Apr 2012 09:03:23 -0400

Builds of the MIPS platform ip32_defconfig fails as of
commit 0195c00244dc2e9f522475868fa278c473ba7339

    "Merge tag 'split-asm_system_h-for-linus-20120328' ..."

because MIPS xchg() macro uses BUILD_BUG_ON and it was moved
in commit b81947c646bfefdf98e2fde5d7d39cbbda8525d4

    "Disintegrate asm/system.h for MIPS"

The root cause is that the system.h split wasn't tested on
a baseline with commit 6c03438edeb5c359af35f060ea016ca65671c269

    "kernel.h: doesn't explicitly use bug.h, so don't include it."

Since this file uses BUG code in several other places besides
the xchg call, simply make the inclusion explicit.

Acked-by: David Howells <dhowells@redhat.com>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
]

3/3 [
Author: Stephen Rothwell
Email: sfr@canb.auug.org.au
Subject: powerpc: fix fallout from system.h split up
Date: Thu, 29 Mar 2012 14:58:10 +1100

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>