NFS: fix 3.19 compile error
strict_strtoul is no longer present in the 3.19 kernel, which results in
the following error:

|   CC      fs/nfs/super.o
| kernel-source/fs/nfs/super.c:
| In function 'nfs_parse_mount_options':
| /kernel-source/fs/nfs/super.c:1388:4:
| error: implicit declaration of function 'strict_strtoul'
| [-Werror=implicit-function-declaration]
|     rc = strict_strtoul(string, 10, &option);
|     ^
|   CC      fs/timerfd.o
|   CC      fs/eventfd.o
| cc1: some warnings being treated as errors

So we update to the replacement kstrtoul.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>