yocto/emgd: emgd 1.14 driver
1/2 [
Author: Nitin A Kamble
Email: nitin.a.kamble@intel.com
Subject: yocto/emgd: emgd 1.14 driver
Date: Mon, 16 Jul 2012 07:14:38 -0700

The starting-point code that subsequent patches will modify.  This is
a straight copy of the code in the emgd 1.14 emgd driver, specifically
IEMGD_HEAD_Linux/common/drm/emgd_drm.tgz from
LIN_IEMGD_1_14_GOLD_2443.tgz, the 'Linux Tar Ball' release downloaded
from http://edc.intel.com/Software/Downloads/EMGD/.

Signed-off-by: Nitin A Kamble <nitin.a.kamble@intel.com>
Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
]

2/2 [
Author: Nitin A Kamble
Email: nitin.a.kamble@intel.com
Subject: emgd/pvr: get it building with v3.4 kernel
Date: Mon, 16 Jul 2012 07:14:50 -0700

Add emgd config option (DRM_EGD) and modify Makefiles for in-tree
builds.

rebased to v3.4 code

Fix build errors caused by changes to kernel interfaces introduced by
linux 3.2 such as:

error: 'THIS_MODULE' undeclared here (not in a function)

due to a missing THIS_MODULE definition which can be found in linux/export.h.

It also fixes a ream of errors like:

error: expected ')' before string constant

due to missing MODULE_PARM_DESC definition which can be found in
linux/moduleparam.h, included by linux/module.h, needed also for
MODULE_AUTHOR, etc.

variable name "pitch" from drm_framebuffer structure has changed
to "pitches" array in v3.4 kernel soruces.

avoid errors like these:
emgd_fbcon.c:128:28: error: 'struct drm_framebuffer' has no member named 'pitch'

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>
Signed-off-by: Nitin A Kamble <nitin.a.kamble@intel.com>
]

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>